apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    jsonData:
      timeInterval: 7s
    editable: true
    isDefault: true
    access: proxy

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
